FROM nvidia/cuda:12.0.1-base-ubuntu20.04
FROM ubuntu:18.04

RUN apt-get update && \
	apt-get install python3.10 && \
	apt-get install -y \
			python3-pip \
			python3-dev \
			ffmpeg

WORKDIR /controller_server
COPY requirements.txt /controller_server/requirements.txt
COPY requirements_serving.txt /controller_server/requirements_serving.txt

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip --no-cache-dir install -r /controller_server/requirements_serving.txt
RUN python3 -m pip --no-cache-dir install -r /controller_server/requirements.txt

COPY ./src /controller_server

# docker build -t mq/controller_ai --load --rm -f Dockerfile_controller .
# docker run -d -p 8000:8000 --name controller_ai mq/controller_ai